name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # or your default branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x' # Specify the Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        pytest # Assuming you use pytest for testing

    - name: Build static files
      run: |
        echo "GITHUB_REPOSITORY: SyedShahmeerAli12/Data_Summarization_NLP" 
        echo "USER: SyedShahmeerAli12" 
        echo "PROJECT_BASE_URL: Data_Summarization_NLP"
        
        # Create the public directory if it doesn't exist
        mkdir -p public
        
        # Copy static files to the public directory
        cp -r templates/* public/
        
        # Example of a build command, replace with your actual build commands if needed
        echo "Building static files for deployment"
        # Add other build steps here if required

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
